# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja"
early_access: false
enable_free_tier: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: @coderabbitai summary
  auto_title_placeholder: @coderabbitai title
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!sandbox/**"
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true