name: build-and-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: |
          make build
  
      - name: Run make check
        run: |
          make run-docker-bg
          make check-webserv
          make clean-docker

      - name: Run tests
        if: github.event_name == 'pull_request'
        run:
          make test
