name: build-and-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
  
      - name: Run build
        run: |
          make build
  
      - name: Run make check
        run: |
          make docker-run
          make docker-check
          make docker-clean

      - name: Run tests
        if: github.event_name == 'pull_request'
        run:
          make test
