name: build-and-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install cppcheck and valgrind
        run: sudo apt-get update && sudo apt-get install -y cppcheck valgrind

      - name: Run make
        run: |
          make check
          make val

      - name: Run tests
        if: github.event_name == 'pull_request'
        run: |
          pytest run_test.py
