name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run make check
        run:
          make check-webserv
      - name: Run tests
        if: github.event_name == 'pull_request'
        run:
          make test-webserv
