name: build-and-routing-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

      - name: Upgrade pip and install pip-tools
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --no-cache-dir pip-tools==7.4.1
      
      - name: Install Python dependencies
        run: |
          pip-compile requirements.in --strip-extras
          pip-sync

      - name: Build webserv
        run: |
          set -e
          make

      - name: Run routing tests
        run: |
          set -e
          pytest -v test/webserv/integration/test_routing.py > test_results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: routing-test-results
          path: routing_test_results.txt
