name: build-and-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install pytest==8.2.2
          sudo apt-get update && sudo apt-get install -y cppcheck=1.90-4build1

      - uses: actions/checkout@v4
      - name: Run make build
        run:
          make build

      - name: Run make check
        run: |
          make run-docker-bg
          sleep 1
          make check-webserv
          sleep 1
          make clean-docker

      - name: Run tests
        if: github.event_name == 'pull_request'
        run:
          make test
