name: run-and-integ-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

      - name: Upgrade pip and install pip-tools
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --no-cache-dir pip-tools==7.4.1
      
      - name: Install Python dependencies
        run: |
          pip-compile requirements.in --strip-extras
          pip-sync

      - name: Run webserv
        run: |
          make run-webserv-for-test

      - name: Wait for webserv to start
        run: |
          sleep 3

      - name: Check whether webserv is running
        run: |
          make is-running

      - name: Run e2e tests
        run: |
          set -e
          make e2e > e2e_test_results.txt

      - name: Upload e2e test results
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-results
          path: e2e_test_results.txt
